services:
  archivewarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archivewarrior
    hostname: archivewarrior
    restart: always
    volumes:
      - ./archivewarrior-config/config.json:/home/warrior/projects/config.json
  tailscaled:
    image: tailscale/tailscale:latest
    container_name: tailscaled-archivewarrior
    restart: always
    environment:
      - TS_STATE_DIR=/var/lib/tailscale/
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale-data:/var/lib/tailscale
      - ./tailscale-tmp:/tmp #To let Caddy speak to TS for TLS
    network_mode: "container:archivewarrior"
    depends_on:
      - archivewarrior
  caddy:
    image: caddy:alpine
    container_name: caddy-archivewarrior
    restart: always
    depends_on:
      - archivewarrior
    network_mode: "container:archivewarrior"
    volumes:
      - ./caddy-data:/data
      - ./caddy-config:/config
      - ./caddy-file/Caddyfile:/etc/caddy/Caddyfile
      - ./tailscale-tmp:/var/run/tailscale #To let Caddy speak to TS for TLS

