- id: '1660713687572'
  alias: Temp Sensor Batteries Died
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.bedroom_temperature
    - sensor.family_room_temperature
    - sensor.living_room_temperature
    - sensor.nursery_temperature
    to: unknown
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_fred
    data:
      message: The Temp Sensor died!
      title: Temp Sensor Failure
  mode: single
