{
 "title": "Connections Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "LFFC : conns1, Estelita's : conns2, Dunlap : conns3, Cafe Red : conns4"
   }
  ]
 },
 "panels": [
  {
   "title": "Calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"futel\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"futel_event\")\n  |> filter(fn: (r) => r[\"endpoint\"] == \"seattle-thistle\" or r[\"endpoint\"] == \"seattle-fortysecond\" or r[\"endpoint\"] == \"seattle-estelitas\" or r[\"endpoint\"] == \"seattle-cafered\")\n  |> filter(fn: (r) => r[\"_value\"] == \"outgoing-dialstatus-completed\")\n  |> group(columns: [\"endpoint\"])\n  |> count(column: \"_field\")\n  |> map(fn: (r) => ({\n    \"Location\": r.endpoint,\n    \"Count\": r._field\n  }))\n  |> sort(columns: [\"Count\"], desc: true)"
    }
   ]
  },
  { "title": "${Node}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "Node" },
  {
   "title": "Pi CPU %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map( fn: (r) => ({r with _value: 100.0 - r._value}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Mikrotik",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\nfrom(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp-wireless-interfaces\")\n  |> filter(fn: (r) => r[\"ssid\"] == \"Connections Community WiFi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"client-count\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> map( fn: (r) => ({r with _value: r._time}))\n  |> experimental.last()"
    }
   ]
  },
  {
   "title": "Calculated Transfer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp-interfaces\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes-out\" or r[\"_field\"] == \"bytes-in\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"if-name\"] == \"wg-shdy\")\n  |> derivative(nonNegative: true, unit: 1s)\n  |> integral(unit: 1s)\n  |> map(fn: (r) => ({ r with _value: r._value / 8.0 }))\n  \n  "
    }
   ]
  },
  {
   "title": "Pi Temp",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Pi",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "ATA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\nfrom(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_trap\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hookStatus1\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> map(fn: (r) => ({\"_time\": r._time, \"_value\": r._value}))\n  |> experimental.last()"
    }
   ]
  },
  {
   "title": "ShadyTel",
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"experimental/json\"\nimport \"strings\"\nfrom(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"shadytel_ifconfig_me\")\n  |> filter(fn: (r) => r[\"_field\"] == \"the_json\")\n  |> map(\n    fn: (r) => ({\n      _time: r._time,\n      _field: r._field,\n      ip_addr: if (strings.index(substr: \"{\", v:r._value,) != 0) then \"∅\" else json.parse(data: bytes(v: r._value)).ip_addr\n    }))\n  |> aggregateWindow(column: \"ip_addr\", every: 2m, fn: last)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp-interfaces\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes-out\" or r[\"_field\"] == \"bytes-in\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"if-name\"] == \"wg-shdy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> derivative(nonNegative: true, unit: 1s)\n  \n  "
    }
   ]
  },
  {
   "title": "Wireless Clients",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp-wireless-interfaces\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"ssid\"] == \"Connections Community WiFi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"client-count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Hook Status",
   "type": "state-timeline",
   "description": "Is the phone on or off the hook?",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mikrotik\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_trap\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Node}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hookStatus1\")\n  |> map(fn: (r) => ({\"_time\": r._time, \"_value\": r._value}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  }
 ]
}