{
 "title": "Power Usage Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_power_source",
    "query": "import \"influxdata/influxdb/v1\"\nv1.measurements(bucket: v.bucket)"
   }
  ]
 },
 "panels": [
  {
   "title": "Circuit Power Consumption",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"homepower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => strings.containsStr(v:r._measurement, substr: \"_wh\") and r[\"_measurement\"] != \"main_total_wh\")\n  |> aggregateWindow(every: 30m, fn: sum, createEmpty: false)\n  |> sum(column: \"_value\")\n  |> group()\n  |> drop(columns: [\"_field\", \"_start\", \"_stop\", \"watt1\", \"watt2\"])"
    }
   ]
  },
  {
   "title": "Power Consumption by Selected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homepower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: 15m, fn: sum)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${selected_power_source}\")"
    }
   ]
  },
  {
   "title": "Total Power Consumption in Period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homepower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> aggregateWindow(every: 60m, fn: sum)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"main_total_kwh\")"
    }
   ]
  },
  {
   "title": "Power Usage 120v",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homepower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] != \"dryer_total\" and r[\"_measurement\"] != \"main_total\" and r[\"_measurement\"] != \"sauna_total\" and r[\"_measurement\"] != \"stove240\" and r[\"_measurement\"] != \"water_heater\" and r[\"_measurement\"] != \"hvac\" and r[\"_measurement\"] != \"watt1_hz\" and r[\"_measurement\"] != \"watt2_hz\")\n  |> aggregateWindow(every: 60s, fn: mean)\n  |> filter(fn: (r) => r[\"_value\"] > 50)\n  |> drop(columns: [\"watt1\", \"watt2\"])\n"
    }
   ]
  },
  {
   "title": "Power Usage 240v",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homepower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dryer_total\" or r[\"_measurement\"] == \"main_total\" or r[\"_measurement\"] == \"sauna_total\" or r[\"_measurement\"] == \"stove240\" or r[\"_measurement\"] == \"water_heater\" or r[\"_measurement\"] == \"hvac\")\n  |> drop(columns: [\"watt1\", \"watt2\"])\n  |> aggregateWindow(every: 60s, fn: mean)\n  \n"
    }
   ]
  },
  {
   "title": "Whole-House Per-Minute Power Consumption in Wh",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"homepower\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"main_total_wh\")\n  |> aggregateWindow(every: 60s, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Whole House Usage (30d)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"homepower\")\n  |> range(start: -30d, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"main_total_kwh\")\n  |> aggregateWindow(every: 24h, fn: sum)\n  \n"
    }
   ]
  }
 ]
}