---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre
    hostname: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - ./calibre-web-config:/config
      - ./books:/books
    restart: unless-stopped
    ports:
      - "8090:8080"
    labels:
      - "traefik.http.routers.calibre.rule=Host(`calibre.hippo-acoustic.ts.net`)"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.http.routers.calibre.entrypoints=cali,calisec"
      - "traefik.http.routers.calibre.tls.certresolver=myresolver"
      - "traefik.enable=true"
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscaled-calibre
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscaledata:/var/lib/tailscale
    network_mode: "container:calibre"
  #  nginx:
    #  image: nginx
    #  container_name: nginx-calibre
    #  restart: unless-stopped
    #  network_mode: "container:calibre"
    #  volumes:
    #  - ./nginxdata/nginx.conf:/etc/nginx/nginx.conf:ro
    #  - ./nginxdata/certs:/etc/ssl/
  traefik:
    image: traefik:latest
    container_name: traefik-calibre
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
        #- "--certificatesresolvers.myresolver.tailscale=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.cali.address=:80"
      - "--entrypoints.calisec.address=:443"
      - "--accesslog"
        #ports:
        #- "8090:8080" #webui
    network_mode: "container:calibre"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

