# Authkey should tag `https`
# On restore from backup/git: update influxdb-config/influx-configs with data from 1Password
# If migrating this service to a new host, the following systems connect locally via HTTP
#   on port 37678, not via Tailscale (so they'll need to be re-pointed):
#   - homeassistant
#   - watt1
#   - watt2

services:
  influxdb:
    container_name: influxdb
    hostname: "influxdb"
    ports:
      - 37678:8086 # Allows local non-Tailscale non-TLS-capable devices to send data into Influx
    image: "influxdb:2-alpine"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    restart: always
  tailscale-power:
    image: tailscale/tailscale
    container_name: tailscaled-power
    restart: always
    depends_on:
      - influxdb
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY:-bad_auth_key}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-data:/var/lib/tailscale
      - tailscale-tmp:/tmp #To let Caddy speak to TS for TLS
    network_mode: "container:influxdb"
  caddy:
    image: caddy:alpine
    container_name: influxdb-caddy
    restart: always
    depends_on:
      - influxdb
    network_mode: "container:influxdb"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./caddy-file/Caddyfile:/etc/caddy/Caddyfile
      - tailscale-tmp:/var/run/tailscale #To let Caddy speak to TS for TLS
volumes:
  tailscale-data:
    name: "powerdata_tailscale-data"
  tailscale-tmp:
    name: "powerdata_tailscale-tmp"
  influxdb-data:
    name: "powerdata_influxdb-data"
  caddy-data:
    name: "powerdata_caddy-data"
  caddy-config:
    name: "powerdata_caddy-config"
