# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

version: '3'
services:
  ssb:
    build: ./go-ssb-room/
    command: 'sh start.sh'
    env_file: .env
    container_name: ssb
    hostname: ssb
    volumes:
      - ./ssb-data:/ssb-go-room-secrets
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscaled-ssb
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale-data:/var/lib/tailscale
    network_mode: "container:ssb"
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx-ssb
    restart: unless-stopped
    network_mode: "container:ssb"
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-data/certs:/etc/ssl/

