services:
  kuma:
    image: louislam/uptime-kuma:2
    restart: always
    hostname: "kuma"
    container_name: kuma
    volumes:
      - ./kuma-data:/app/data
  tailscaled:
    image: tailscale/tailscale
    container_name: tailscaled-kuma
    restart: always
    depends_on:
      - kuma
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale-data:/var/lib/tailscale
      - ./tailscale-tmp:/tmp #To let Caddy speak to TS for TLS
    network_mode: "container:kuma"

  caddy:
    image: caddy:alpine
    container_name: caddy-kuma
    restart: always
    depends_on:
      - kuma
    network_mode: "container:kuma"
    volumes:
      - ./caddy-data:/data
      - ./caddy-config:/config
      - ./caddy-file/Caddyfile:/etc/caddy/Caddyfile
      - ./tailscale-tmp:/var/run/tailscale #To let Caddy speak to TS for TLS
