version: '3'
services:
  pocorgtfo:
    container_name: pocorgtfo
    hostname: pocorgtfo
    image: caddy:alpine
    volumes:
      - ./caddy-data:/data
      - ./caddy-config:/config
      - ./caddy-www:/var/www
      - ./caddy-file/Caddyfile:/etc/caddy/Caddyfile
      - ./tailscale-tmp:/var/run/tailscale #To let Caddy speak to TS for TLS
    restart: unless-stopped
    ports:
      - "8111:443"
  tailscaled:
    image: tailscale/tailscale:latest
    container_name: tailscaled-pocorgtfo
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale/
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale-tmp:/tmp #To let Caddy speak to TS for TLS
      - ./tailscale-data:/var/lib/tailscale
    network_mode: "container:pocorgtfo"


